version: "3.8"
services:

  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_USER: scheduler
      MYSQL_PASSWORD: scheduler!@#
      MYSQL_DATABASE: scheduler
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: database-volume
        target: /var/lib/mysql
    networks:
      - scheduler-network

  scheduler-back:
    build:
      context: scheduler-back
      dockerfile: Dockerfile
    image: scheduler-back:latest
    environment:
      TZ: "America/Sao_Paulo"
      LC_ALL: "pt_BR.UTF-8"
      LANG: "pt_BR.UTF-8"
      LANGUAGE: "pt_BR:UTF-8"
    networks:
      - scheduler-network
    depends_on:
      - db

  scheduler-front:
    build:
      context: scheduler-front
      dockerfile: Dockerfile
    image: scheduler-front:latest
    environment:
      TZ: "America/Sao_Paulo"
      LC_ALL: "pt_BR.UTF-8"
      LANG: "pt_BR.UTF-8"
      LANGUAGE: "pt_BR:UTF-8"
    networks:
      - scheduler-network

  nginx-external:
    build:
      context: nginx/external
      dockerfile: Dockerfile
    image: nginx-external:latest
    networks:
      - scheduler-network
    environment:
      TZ: "America/Sao_Paulo"
    tty: true
    ports:
      - "9090:443"
      - "8080:80"
    depends_on:
      - scheduler-front

  nginx-internal:
    build:
      context: nginx/internal
      dockerfile: Dockerfile
    image: nginx-internal:latest
    networks:
      - scheduler-network
    environment:
      TZ: "America/Sao_Paulo"
    tty: true
    ports:
      - "555:555"
    depends_on:
      - scheduler-front
      - scheduler-back

networks:
  scheduler-network:

volumes:
  database-volume: