version: "3.8"
services:

  scheduler-back:
    build:
      dockerfile: scheduler-back/Dockerfile
    image: scheduler-back:latest
    environment:
      TZ: "America/Sao_Paulo"
      LC_ALL: "pt_BR.UTF-8"
      LANG: "pt_BR.UTF-8"
      LANGUAGE: "pt_BR:UTF-8"
    networks:
      - scheduler-network

  scheduler-front:
    build:
      dockerfile: scheduler-front/Dockerfile
    image: scheduler-back:lastest
    environment:
      TZ: "America/Sao_Paulo"
      LC_ALL: "pt_BR.UTF-8"
      LANG: "pt_BR.UTF-8"
      LANGUAGE: "pt_BR:UTF-8"
    networks:
      - scheduler-network

  nginx:
    build:
      dockerfile: Dockerfile
    image: nginx
    networks:
      - scheduler-network
    environment:
      TZ: "America/Sao_Paulo"
    tty: true
    ports:
      - "9090:443"
      - "8080:80"

networks:
  scheduler-network: