spring:
  profiles:
    active: prod
  jpa:
    open-in-view: 'false'
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
    enabled-by-default: 'false'
  endpoint:
    health:
      enabled: 'true'
      show-details: always
    prometheus:
      enabled: 'true'

---

