spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler
#    url: jdbc:mysql://67.205.170.183:3306/scheduler
    username: scheduler
    password: scheduler!@#
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace