spring:
    profiles:
        active: prod
    jpa:
        open-in-view: "false"
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: none

    flyway:
        enabled: true
        baseline-on-migrate: true

management:
    endpoints:
        web:
            exposure:
                include: health,prometheus
        access:
            default: none
    endpoint:
        health:
            show-details: always
            access: unrestricted
        prometheus:
            access: unrestricted
app:
    security:
        jwt-issuer: "scheduler"
